//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alien.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class alien
    {
        public int id { get; set; }
        public string GeneticCode { get; set; }
        public string AlienBreed { get; set; }
        public string AlienPlanet { get; set; }
        public Nullable<int> AlienExpectedAge { get; set; }
        public string AlienMission { get; set; }
    }
}
