//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookRecor.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRecord
    {
        public int id { get; set; }
        public string name { get; set; }
        public string Author { get; set; }
        public Nullable<int> publishYear { get; set; }
        public Nullable<int> preBooking { get; set; }
    }
}
