//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableRegistration.Services
{
    using System;
    using System.Collections.Generic;

    public class AvailService
    {
        public int tableId { get; set; }
        public string ChoosenServices { get; set; }
    } public class AvailVenue
    {
        public int tableId { get; set; }
        public string Venue { get; set; }
    }
    public partial class BookTable
    {
        public BookTable()
        {
            this.VenueNameList = new List<AvailVenue>
            {
                new AvailVenue {Venue = "Noida", tableId= 1},

                new AvailVenue {Venue = "Gurugram", tableId =2},
                new AvailVenue {Venue = "Faridabad", tableId = 3},
                new AvailVenue {Venue = "Haryana", tableId=4},
                new AvailVenue {Venue = "Mathura",tableId=5},
                new AvailVenue {Venue = "New Delhi", tableId=6}
            };
            this.ServiceNameList = new List<AvailService>
            {
                new AvailService {ChoosenServices = "Ac", tableId=1},
                new AvailService {ChoosenServices = "Non Ac", tableId=2},
                new AvailService {ChoosenServices = "Family Budget Pack", tableId=3},
                new AvailService {ChoosenServices = "With Smoking Zone", tableId=4},
                new AvailService {ChoosenServices = "On Terrace", tableId=5}
            };
        }
        public string YourName { get; set; }
    
        public string Venue { get; set; }
        public Nullable<bool> Agreed { get; set; }
        public Nullable<int> NumberOfPleople { get; set; }
        public string ChoosenServices { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<System.TimeSpan> ReachingTime { get; set; }
        public Nullable<System.DateTime> Bookingdate { get; set; }
        public int tableId { get; set; }
        public List<AvailService> ServiceNameList { get; set; }
        public List<AvailVenue> VenueNameList { get; set; }
    }
}
