//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excellent.Training.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerRecord
    {
        public string PlayerName { get; set; }
        public int PlayerRank { get; set; }
        public Nullable<int> PlayerScore { get; set; }
        public string PlayerTeam { get; set; }
        public string PlayerSport { get; set; }
        public Nullable<int> playerJurseyNo { get; set; }
    }
}
