//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdRecord.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bird
    {
        public string Name { get; set; }
        public Nullable<double> DistTravelled { get; set; }
        public string MigratingTo { get; set; }
        public string MigratingFrom { get; set; }
        public Nullable<double> TimeTaken { get; set; }
        public int id { get; set; }
    }
}
